version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 073645649421.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose --file=docker-compose.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images....
      - docker-compose --file=docker-compose.yml push
artifacts:
    files: 
      - 'docker-compose.yml'
