version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo "$REGION"
      - cat ./pipeline_config/test_file.yml
      - python3 ./pipeline_config/scripts/replace_token.py
      - echo replacing tokens
      - cat ./pipeline_config/test_file.yml
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_ARN
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
#       - docker-compose --file=docker-compose.yml build
  post_build:
    commands:
      - echo Build completd on `date`
      - echo Pushing the Docker images....
#       - docker-compose --file=docker-compose.yml push
artifacts:
    files: 
      - '**/*'
